name: Deploy CI/CD to Server
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing deploy to server using remote ssh key
        uses: appleboy/ssh-action@master
        with:
          host: "sabilunnashr.com"
          port: "2223"
          key: "AAAAB3NzaC1yc2EAAAADAQABAAABAQDDflqSlUJOpGi4GOJ9k0/WD4zX2EUG89gf2vD56uJtuZINEi+AV4e+yfqYpRgHpequKixwjzytaxnahdAZjxZx8HLjnYJ4BRhdIbqbEO0/ZEKO1ybgX9OJ2MDyRsxtSNmCP6hxksOkpvxawu5p2lOCAH3BShTk/useqlQvqWg+qJWzuV9tXL1x5f00u/9wddiXtu/tJnY05JAzbhOXiTUNsdxVB1Y2l6nsYFLfw4CjWrGvXDKJ5/VmLPxgM6WLuyh0EGmZngyTlOjZBwSloL/6SeSdmnO8N9hty5txmhIMZLN0/MYj/sbDQWlJVCqMSy8l0oKyiR7pQFiJuRHP+xkd"
          username: "sabj8295"
          password: "Passwordku123"
          # host: ${{ secrets.HOST }}
          # username: ${{ secrets.USERNAME }}
          # password: ${{ secrets.PASSWORD }}
          # port: ${{ secrets.PORT }}
          # key: ${{ secrets.key }}
          script: |
            cd /home/sabj8295/Sabilunnashr/
            git pull origin main
            cp -r dist/* ../public_html/
